---
version: '3.2'
services:
  traefik:
    build:
      context: images/traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "BACKUP_DEST=s3://${ACME_BUCKET_NAME}"
      - "BACKUP_ENDPOINT=https://sos-${EXOSCALE_REGION}.exo.io"
      - "BACKUP_BUCKETURL=%(bucket)s.sos-${EXOSCALE_REGION}.exo.io"
      - "EXOSCALE_KEY=${EXOSCALE_KEY}"
      - "EXOSCALE_SECRET=${EXOSCALE_SECRET}"
    networks:
      internal:
        ipv4_address: 172.28.1.2
    restart: always
  nginx:
    build:
      context: images/nginx
    volumes:
      - /srv/www:/var/www
    labels:
      traefik.enable: "true"
      traefik.backend: "nginx"
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.port: "80"
      traefik.protocol: "http"
      traefik.frontend.headers.SSLTemporaryRedirect: "false"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.forceSTSHeader: "false"
    restart: always
    networks:
      internal:
        ipv4_address: 172.28.1.3
  pull:
    build:
      context: images/pull
    environment:
      - "PULL_SOURCE=s3://${CONTENT_BUCKET_NAME}"
      - "PULL_ENDPOINT=https://sos-${EXOSCALE_REGION}.exo.io"
      - "PULL_BUCKETURL=%(bucket)s.sos-${EXOSCALE_REGION}.exo.io"
      - "EXOSCALE_KEY=${EXOSCALE_KEY}"
      - "EXOSCALE_SECRET=${EXOSCALE_SECRET}"
    volumes:
      - /srv/www:/var/www
      - /srv/monitoring:/srv/monitoring
    networks:
      internal:
        ipv4_address: 172.28.1.4
    restart: always
  backup:
    build:
      context: images/backup
    environment:
      - "ACME_BACKUP_DEST=s3://${ACME_BUCKET_NAME}"
      - "PROMETHEUS_BACKUP_DEST=s3://${PROMETHEUS_BUCKET_NAME}"
      - "BACKUP_ENDPOINT=https://sos-${EXOSCALE_REGION}.exo.io"
      - "BACKUP_BUCKETURL=%(bucket)s.sos-${EXOSCALE_REGION}.exo.io"
      - "EXOSCALE_KEY=${EXOSCALE_KEY}"
      - "EXOSCALE_SECRET=${EXOSCALE_SECRET}"
    volumes:
      - /srv/acme:/srv/acme
      - /srv/prometheus:/srv/prometheus
      - /srv/grafana:/srv/grafana
      - /srv/monitoring:/srv/monitoring
    networks:
      internal:
        ipv4_address: 172.28.1.5
    restart: always
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.3.0
    command:
      - "-nginx.scrape-uri"
      - "http://nginx:80/.well-known/nginx/basic_status"
    networks:
      internal:
        ipv4_address: 172.28.1.6
    restart: always
    depends_on:
      - nginx
  node-exporter:
    image: quay.io/prometheus/node-exporter
    pid: "host"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs"
      - "/host"
      - "--collector.systemd"
      - "--collector.textfile"
      - "--collector.textfile.directory=/host/srv/monitoring"
      - "--web.listen-address=172.28.0.1:9100"
    network_mode: host
    restart: always
  cadvisor:
    image: google/cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      internal:
        ipv4_address: 172.28.1.8
    restart: always
  prometheus:
    build:
      context: images/prometheus
    ports:
      - "9090:9090"
    networks:
      internal:
        ipv4_address: 172.28.1.9
    volumes:
      - "/srv/prometheus:/prometheus"
    environment:
      - "BACKUP_DEST=s3://${PROMETHEUS_BUCKET_NAME}"
      - "BACKUP_ENDPOINT=https://sos-${EXOSCALE_REGION}.exo.io"
      - "BACKUP_BUCKETURL=%(bucket)s.sos-${EXOSCALE_REGION}.exo.io"
      - "EXOSCALE_KEY=${EXOSCALE_KEY}"
      - "EXOSCALE_SECRET=${EXOSCALE_SECRET}"
    restart: always
    depends_on:
      - nginx-exporter
      - node-exporter
  php:
    build:
      context: images/php
    volumes:
      - /srv/www:/var/www
    restart: always
    networks:
      internal:
        ipv4_address: 172.28.1.10
  grafana:
    build:
      context: images/grafana
    environment:
      - "GF_SERVER_DOMAIN=monitoring.${DOMAIN}"
      - "GF_SERVER_ROOT_URL=https://monitoring.${DOMAIN}"
      - "GF_SERVER_ENFORCE_DOMAIN=true"
      - "GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin"
      - "GF_USERS_AUTO_ASSIGN_ORG=true"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_NAME=Main Org."
      - "GF_AUTH_GITHUB_ENABLED=true"
      - "GF_AUTH_GITHUB_SCOPES=user:email,read:org"
      - "GF_AUTH_GITHUB_AUTH_URL=https://github.com/login/oauth/authorize"
      - "GF_AUTH_GITHUB_TOKEN_URL=https://github.com/login/oauth/access_token"
      - "GF_AUTH_GITHUB_API_URL=https://api.github.com/user"
      - "GF_AUTH_GITHUB_ALLOW_SIGNUP=true"
      - "GF_AUTH_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}"
      - "GF_AUTH_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}"
      - "GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS=opsbears"
      - "GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}"
      - "GF_SECURITY_COOKIE_SECURE=true"
      - "GF_SECURITY_COOKIE_SAMESITE=true"
      - "GF_ANALYTICS_REPORTING_ENABLED=false"
      - "BACKUP_ENDPOINT=https://sos-${EXOSCALE_REGION}.exo.io"
      - "BACKUP_BUCKETURL=%(bucket)s.sos-${EXOSCALE_REGION}.exo.io"
      - "EXOSCALE_KEY=${EXOSCALE_KEY}"
      - "EXOSCALE_SECRET=${EXOSCALE_SECRET}"
    volumes:
      - "/srv/grafana:/var/lib/grafana"
    labels:
      traefik.enable: "true"
      traefik.backend: "grafana"
      traefik.frontend.rule: "Host:monitoring.${DOMAIN}"
      traefik.port: "3000"
      traefik.protocol: "http"
      traefik.frontend.headers.SSLTemporaryRedirect: "false"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.forceSTSHeader: "false"
      traefik.frontend.redirect.regex: "^https://monitoring.${DOMAIN}/$$"
      traefik.frontend.redirect.replacement: "https://monitoring.${DOMAIN}/d/mXFB_yRWz/home?orgId=1"
      traefik.frontend.redirect.permanent: "true"
    restart: always
    networks:
      internal:
        ipv4_address: 172.28.1.11
networks:
  internal:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.28.0.0/16
